/*
 * OpenAPI Echo
 * This spec is to test issue 910
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Md5;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Print md5
     *
     * md5
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getmd5Test() throws ApiException {
        String text = null;
        Md5 response = api.getmd5(text).block();

        // TODO: test validations
    }
    
}
