/*
 * OpenAPI Echo
 * This spec is to test issue 910
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.Md5;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for DefaultApi
 */
@Ignore
public class Issue909Test {


  /**
   * Print echo
   *
   * echo
   *
   */
  @Test
  public void getEchoEqualsTest() {
    DefaultApi api = new DefaultApi();
    Md5 response = api.getmd5("test_with_equals=").block();

    assertNotNull(response);
    assertEquals( "test_with_equals=", response.getOriginal());
  }

  @Test
  public void getEchoSpecialCharsTest() {
    DefaultApi api = new DefaultApi();
    String test = "|!$%&/()=?^";
    Md5 response = api.getmd5(test).block();

    assertNotNull(response);
    assertEquals(test, response.getOriginal());
  }
}
