/*
 * OpenAPI Echo
 * This spec is to test issue 910
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import java.time.OffsetDateTime;
import org.openapitools.client.ApiException;
import org.openapitools.client.model.Echo;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for DefaultApi
 */
@Ignore
public class Issue910Test {

  private final DefaultApi api = new DefaultApi();


  /**
   * Print echo
   *
   * echo
   *
   */
  @Test
  public void getEchoTest() {

    Echo response = api.getEcho("2017-02-03T12:30:30+01:00").block();

    assertNotNull(response);
    assertEquals(response.getTestDate(), OffsetDateTime.parse("2017-02-03T12:30:30+01:00"));
  }

}
